/****** Object:  Table [dbo].[CachesSQL]    Script Date: 16/10/2021 12:27:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CachesSQL](
	[ID] [int] NOT NULL,
	[NomeCache] [nvarchar](255) NULL,
	[Descricao] [nvarchar](255) NULL,
	[Ultalt] [datetime] NULL,
 CONSTRAINT [PK_CachesSQL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


